# version: "3.8"

services:
  papi_backend:
    build: ./papi_backend
    image: papi_backend:latest
    container_name: papi_backend
    ports:
      - "8443:8443"
    networks:
      - personal_api
    environment:
      - PAPI_LINE_SERVER_ENDPOINT=http://papi_line:6969/download
      - AUTHORIZATION_DB_URI=mongodb://authorization_db:27017/authorizations
    env_file:
      - ./papi_backend/.env
    depends_on:
      - papi_line

  papi_line:
    build: ./papi_line
    image: papi_line:latest
    container_name: papi_line
    # papi_line should be accessible only from papi_backend
    # ports:
    #   - "6969:6969"
    networks:
      - personal_api
    env_file:
      - ./papi_line/.env
    depends_on:
      - authorization_db

  authorization_db:
    image: mongo:latest
    container_name: authorization_db
    # authorization_db should be accessible only from papi_backend
    # ports:
    #   - "27017:27017"
    networks:
      - personal_api
    volumes:
      - ./papi_db:/data/db
networks:
  personal_api:
    driver: bridge

x-podman:
  podname: papi_pod
